### ISSUE TITLE
Expose $resource.query 

### ISSUE THREAD

**Issue by jimmypoms** [zerodine/angular-restclient#1]
Since we are using array responses in our API, it would be nice to expose the query function in order to easily use array responses.

**Comment by philippspinnler** [comment]
Do I understand this right: You want .query to handle array responses and .get object responses?

**Comment by jimmypoms** [comment]
Yes.
I figured this is the fastest/cleanest way to not change the existing codebase. Also it appears to me that this is how $resource handles it out of the box.

however, I'm open to critique :)

**Comment by philippspinnler** [comment]
You are right :) Let me just check that with the rest of the code base and I will implement it.

**Comment by jimmypoms** [comment]
Thanks :) ... and cheers from Rapperswil ;)

**Comment by philippspinnler** [comment]
Tom and I talked about it and we came up with an other approach. To not be confused when to use .get and when to use .query we extended the .get method with the isArray parameter. Because it would be a pain to define this in every call we extended the endpoint config as well with the .isArray() method. An endpoint in your case would look like this:

```
apiProvider.endpoint('users')
.route('/users')
.model('User')
.isArray();
```

We think that this is less confusing and better to read. What do you think?

**Comment by jimmypoms** [comment]
First of all, thank you for providing a solution for the given problem :+1: :).

While I do agree that exposing the query method is a rather pragmatic than pretty solution, I feel like your approach is a tad specific ;).

I know it might be a bit off topic, but I would like to get your take on the idea. How about offering a more general way of describing the endpoint?

```js
apiProvider.endpoint('users')
.route('/users')
.model('User')
.actions({
  get: {isArray: true}
});
```

Admittedly a rather cumbersome solution for the task at hand, but as a huge benefit, it allows you to leverage the power of $resource (think about custom interceptors or custom actions like search for a specific endpoint).

**Comment by philippspinnler** [comment]
Good idea. I tried it and got stuck at some point. Can you tell me how your response looks like when you request a specific resource (e.g. /users/312). Is it an object or an array?

I think I maybe redesign the endpoint to automatically detect if the response is an object or an array. That could solve a lot of problems.

**Comment by philippspinnler** [comment]
I redesigned the endpoint. Every response is now auto-detected and the isArray is no longer needed. I wrote an additional test for this case an it passes. Nevertheless its possible to configure the actions on a endpoint like you suggested.  What do you think?

**Comment by jimmypoms** [comment]
Nice one :).

I feel like this is a very nice solution which offers an additional set of features without compromising the existing ones. I will test it on our setup in the next few days :)

**Comment by jimmypoms** [comment]
Seems to be working correctly with one exception:
- if the server response is not a model object (e.g. validation errors, success message), it tries to box it into the model resulting in an empty model and loss of the original response

A solution to this might be checking the status in `transformResponse` to be 2xx. Although not documented in $resource, I assume the third argument to `transformResponse` is the status, same as mentioned in the documentation to $http.

Additionally, how would you recommend dealing with success responses (e.g. api call to /tickets/12/close). Since there is a 2xx response code but no model data returned, this does not fit well with the current implementation :(.
Again a bit off topic, but what do you guys think about making the model configuration optional. This would result in the following being a valid endpoint config:
```
apiProvider.endpoint('posts')
    .route('/posts/:id');
```

P.S: Sorry for being such a demanding user :)
